@echo off
echo Parando robo...
powershell -Command "Get-CimInstance Win32_Process | Where-Object { ($_.Name -eq 'python.exe') -and ($_.CommandLine -match 'main.py|interface\\app.py') } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }"
echo Parando sincronizacao...
powershell -Command "Get-CimInstance Win32_Process | Where-Object { ($_.Name -eq 'powershell.exe') -and ($_.CommandLine -match 'sincronizar_aws.ps1') } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }"
echo Limpando navegador do robo...
powershell -Command "Get-CimInstance Win32_Process | Where-Object { ($_.Name -eq 'chrome.exe') -and ($_.CommandLine -match 'ml_profile_stealth|playwright|_internal') } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }"
echo Finalizado
pause