# ui/theme.py

APP_NAME = "TH IA MOTOS"
APP_VERSION = "v1.0"

# Cores principais
COLOR_BG = "#0B1220"
COLOR_SIDEBAR = "#070D18"
COLOR_CONTENT = "#0F172A"
COLOR_CARD = "#111827"
COLOR_CARD_HOVER = "#1F2937"

# Cores de destaque
COLOR_GREEN = "#22C55E"
COLOR_GREEN_DARK = "#16A34A"
COLOR_BLUE = "#38BDF8"
COLOR_PURPLE = "#A855F7"
COLOR_YELLOW = "#FACC15"
COLOR_RED = "#EF4444"

# Texto
COLOR_TEXT = "#F9FAFB"
COLOR_TEXT_MUTED = "#9CA3AF"

# Bordas
COLOR_BORDER = "#1F2937"

# Fontes
FONT_TITLE = ("Arial", 28, "bold")
FONT_SUBTITLE = ("Arial", 15)
FONT_SECTION = ("Arial", 20, "bold")
FONT_CARD_TITLE = ("Arial", 14)
FONT_CARD_VALUE = ("Arial", 24, "bold")
FONT_BUTTON = ("Arial", 14, "bold")
FONT_SMALL = ("Arial", 11)

# Sidebar
COLOR_ACTIVE = "#1E40AF"
COLOR_SIDEBAR_HOVER = "#1F2937"

# Logo
LOGO_IMAGE = None

# Compatibilidade visual
COLOR_PRIMARY = COLOR_GREEN
COLOR_PRIMARY_HOVER = COLOR_GREEN_DARK

# Compatibilidade para componentes novos
COLOR_PRIMARY = COLOR_GREEN
COLOR_PRIMARY_HOVER = COLOR_GREEN_DARK
COLOR_ACTIVE = "#1E40AF"
COLOR_SIDEBAR_HOVER = "#1F2937"
COLOR_DIVIDER = COLOR_BORDER
LOGO_IMAGE = None